Revert "AttributeError: 'ParentAlternativelyMappedMapping' object has no attribute 'level_one_attribute'"
This reverts commit 5486b456e678f428c6035f176ff7aa9976be4d4e.